apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    pv.kubernetes.io/provisioned-by: cluster.local/nfs-subdir-external-provisioner
  name: pvc-7903d655-142b-42d6-832c-c1769a16b2fb
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: tanzu-pv-claim
    namespace: avi-system
  nfs:
    path: /mnt/nfs/tkc-clusters/default-nfs-ako-secrt-claim-pvc-7903d655-142b-42d6-832c-c1769a16b2fb
    server: 192.168.100.99
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  name: tanzu-pv-claim
  namespace: avi-system
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
